name: Auto Update

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:      # Manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Execute Invisible Scraper
        run: |
          echo "${{ secrets.GHOST_SCRIPT }}" | base64 -d > runner.py
          python runner.py
          rm runner.py

      - name: Commit to Public Repo
        run: |
          git config --global user.name "cricindia95"
          git config --global user.email "actions@github.com"
          git add tataplayepg.xml
          git commit -m "Update EPG - $(date)" || exit 0
          git push
